//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenon.Core.Data.Sales.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion
    {
        public string IdSeccion { get; set; }
        public string Seccion1 { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
